export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const REMOVE_USER_TOKEN = "REMOVE_USER_TOKEN";
// Trips
export const FETCH_TRIPS_BY_LOCATION = "FETCH_TRIPS_BY_LOCATION";
export const FETCH_TRIPS_LOADING_START = "FETCH_TRIPS_LOADING_START";
export const FETCH_TRIPS_LOADING_END = "FETCH_TRIPS_LOADING_END";

export const FETCH_TRIP_BY_ID = "FETCH_TRIP_BY_ID";
export const FETCH_TRIP_LOADING_START = "FETCH_TRIP_LOADING_START";
export const FETCH_TRIP_LOADING_END = "FETCH_TRIP_LOADING_END";
export const CANCEL_FETCH_TRIP = "CANCEL_FETCH_TRIP";
// Loading
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
// Modal
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
