export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const REMOVE_USER_TOKEN = "REMOVE_USER_TOKEN";
// Trips
export const FETCH_TRIPS_BY_LOCATION = "FETCH_TRIPS_BY_LOCATION";
export const FETCH_TRIPS_LOADING_START = "FETCH_TRIPS_LOADING_START";
export const FETCH_TRIPS_LOADING_END = "FETCH_TRIPS_LOADING_END";

export const FETCH_TRIP_BY_ID = "FETCH_TRIP_BY_ID";
export const FETCH_TRIP_LOADING_START = "FETCH_TRIP_LOADING_START";
export const FETCH_TRIP_LOADING_END = "FETCH_TRIP_LOADING_END";
export const CANCEL_FETCH_TRIP = "CANCEL_FETCH_TRIP";
// Commment
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const ADD_COMMENT_LOADING_START = "COMMENT_LOADING_START";
export const ADD_COMMENT_LOADING_END = "ADD_COMMENT_LOADING_END";
export const DELETE_COMMENT_LOADING_START = "DELETE_COMMENT_LOADING_START";
export const DELETE_COMMENT_LOADING_END = "DELETE_COMMENT_LOADING_END";
// Rate
export const RATE_TRIP = "RATE_TRIP";
export const RATE_TRIP_LOADING_START = "RATE_TRIP_LOADING_START";
export const RATE_TRIP_LOADING_END = "RATE_TRIP_LOADING_END";
// Loading
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
// Modal
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
// Error
export const ERROR = "ERROR";
// Booking
export const BOOKING = "BOOKING";
export const BOOKING_LOADING_START = "BOOKING_LOADING_START";
export const BOOKING_LOADING_END = "BOOKING_LOADING_END";
